/*
 * University College, University of Denver student project.
 * Not intended for production or distribution.
 * Java Programming ICT4361-1.
 * Author: Raymond G Menasche
 */
package edu.du.menascheraymond.view;

import edu.du.menascheraymond.controller.maincontroller.MainController;
import edu.du.menascheraymond.model.business.command.Command;
import edu.du.menascheraymond.model.business.factory.CommandFactory;
import edu.du.menascheraymond.model.business.factory.CommandFactoryImpl;
import edu.du.menascheraymond.model.business.manager.Manager;
import edu.du.menascheraymond.model.services.PersistenceService;
import java.util.List;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JScrollPane;
import javax.swing.JTextField;


/**
 *
 * @author raymond
 */
public class MainMenuFrame extends javax.swing.JFrame {

    private Manager manager = new Manager();
    
    /**
     * Creates new form CarShowFrame
     */
    public MainMenuFrame() {
        initComponents();
        MainController mainController = new MainController(this);
        PersistenceService ps = manager.getPersistenceService();
        List<Map<String,String>> commands = ps.getCommands();
        for (Map<String,String> cmd: commands) {
            
            CommandFactory cf = new CommandFactoryImpl();
            Command command = cf.getCommand(cmd.get("TYPE"));
            if (command != null) {
                command.setManager(manager);
                command.performCommands(cmd);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ownerSearchField = new javax.swing.JTextField();
        ownerSearchButton = new javax.swing.JButton();
        ownerSearchResultLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carShowOwnerList = new javax.swing.JList<>();
        CarShowOwnerListLabel = new javax.swing.JLabel();
        removeCarShowOwnerButton = new javax.swing.JButton();
        carShowSearchField = new javax.swing.JTextField();
        carShowSearchButton = new javax.swing.JButton();
        carShowSearchResultLabel = new javax.swing.JLabel();
        addCarShowOwnerButton = new javax.swing.JButton();
        carShowMainMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        undoResetMenuItem = new javax.swing.JMenuItem();
        objectsMenu = new javax.swing.JMenu();
        ownerMenuItem = new javax.swing.JMenuItem();
        vehicleMenuItem = new javax.swing.JMenuItem();
        carShowMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Show Admin");

        ownerSearchField.setText("Enter Owner ID");

        ownerSearchButton.setText("Search");

        ownerSearchResultLabel.setText("Display Owner Resutl");

        jScrollPane1.setViewportView(carShowOwnerList);

        CarShowOwnerListLabel.setText("Owner's Car Shows");

        removeCarShowOwnerButton.setText("Remove");

        carShowSearchField.setText("Enter Car Show ID");

        carShowSearchButton.setText("Search");

        carShowSearchResultLabel.setText("Display Car Show Result");

        addCarShowOwnerButton.setText("Add");

        fileMenu.setText("File");

        exitItem.setText("Exit");
        fileMenu.add(exitItem);

        carShowMainMenu.add(fileMenu);

        editMenu.setText("Edit");

        undoResetMenuItem.setText("Undo/Reset");
        undoResetMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoResetMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(undoResetMenuItem);

        carShowMainMenu.add(editMenu);

        objectsMenu.setText("Objects");

        ownerMenuItem.setText("Owner");
        ownerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerMenuItemActionPerformed(evt);
            }
        });
        objectsMenu.add(ownerMenuItem);

        vehicleMenuItem.setText("Vehicle");
        vehicleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleMenuItemActionPerformed(evt);
            }
        });
        objectsMenu.add(vehicleMenuItem);

        carShowMenuItem.setText("Car Show");
        carShowMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carShowMenuItemActionPerformed(evt);
            }
        });
        objectsMenu.add(carShowMenuItem);

        carShowMainMenu.add(objectsMenu);

        setJMenuBar(carShowMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ownerSearchResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ownerSearchField)
                            .addComponent(carShowSearchField)
                            .addComponent(carShowSearchResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ownerSearchButton)
                            .addComponent(carShowSearchButton)))
                    .addComponent(addCarShowOwnerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeCarShowOwnerButton)
                    .addComponent(CarShowOwnerListLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ownerSearchButton)
                        .addComponent(ownerSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CarShowOwnerListLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ownerSearchResultLabel)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carShowSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carShowSearchButton))
                        .addGap(26, 26, 26)
                        .addComponent(carShowSearchResultLabel)
                        .addGap(18, 18, 18)
                        .addComponent(addCarShowOwnerButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(removeCarShowOwnerButton)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ownerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerMenuItemActionPerformed
        OwnerFrame ownerFrame = new OwnerFrame();
        ownerFrame.setVisible(true);
    }//GEN-LAST:event_ownerMenuItemActionPerformed

    private void vehicleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleMenuItemActionPerformed
        VehicleFrame vehicleFrame = new VehicleFrame();
        vehicleFrame.setVisible(true);
    }//GEN-LAST:event_vehicleMenuItemActionPerformed

    private void carShowMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carShowMenuItemActionPerformed
        CarShowFrame carShowFrame = new CarShowFrame();
        carShowFrame.setVisible(true);
    }//GEN-LAST:event_carShowMenuItemActionPerformed

    private void undoResetMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoResetMenuItemActionPerformed
        // TODO add your handling code here: Reload data from persistance
    }//GEN-LAST:event_undoResetMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void runApplication() throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainMenuFrame().setVisible(true);
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        });
    }

    public JButton getAddCarShowOwnerButton() {
        return addCarShowOwnerButton;
    }

    public JMenuBar getCarShowMainMenu() {
        return carShowMainMenu;
    }

    public JMenuItem getCarShowMenuItem() {
        return carShowMenuItem;
    }

    public JList<String> getCarShowOwnerList() {
        return carShowOwnerList;
    }

    public JButton getCarShowSearchButton() {
        return carShowSearchButton;
    }

    public JTextField getCarShowSearchField() {
        return carShowSearchField;
    }
    
    public JLabel getCarShowSearchResultLabel() {
        return carShowSearchResultLabel;
    }

    public JMenu getEditMenu() {
        return editMenu;
    }

    public JMenuItem getExitItem() {
        return exitItem;
    }

    public JMenu getFileMenu() {
        return fileMenu;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JMenu getObjectsMenu() {
        return objectsMenu;
    }

    public JMenuItem getOwnerMenuItem() {
        return ownerMenuItem;
    }

    public JButton getOwnerSearchButton() {
        return ownerSearchButton;
    }

    public JTextField getOwnerSearchField() {
        return ownerSearchField;
    }

    public JLabel getOwnerSearchResultLabel() {
        return ownerSearchResultLabel;
    }

    public JButton getRemoveCarShowOwnerButton() {
        return removeCarShowOwnerButton;
    }

    public JMenuItem getUndoResetMenuItem() {
        return undoResetMenuItem;
    }

    public JMenuItem getVehicleMenuItem() {
        return vehicleMenuItem;
    }
    
    public Manager getManager() {
        return manager;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CarShowOwnerListLabel;
    private javax.swing.JButton addCarShowOwnerButton;
    private javax.swing.JMenuBar carShowMainMenu;
    private javax.swing.JMenuItem carShowMenuItem;
    private javax.swing.JList<String> carShowOwnerList;
    private javax.swing.JButton carShowSearchButton;
    private javax.swing.JTextField carShowSearchField;
    private javax.swing.JLabel carShowSearchResultLabel;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu objectsMenu;
    private javax.swing.JMenuItem ownerMenuItem;
    private javax.swing.JButton ownerSearchButton;
    private javax.swing.JTextField ownerSearchField;
    private javax.swing.JLabel ownerSearchResultLabel;
    private javax.swing.JButton removeCarShowOwnerButton;
    private javax.swing.JMenuItem undoResetMenuItem;
    private javax.swing.JMenuItem vehicleMenuItem;
    // End of variables declaration//GEN-END:variables
    

}
