/*
 * University College, University of Denver student project.
 * Not intended for production or distribution.
 * Java Programming ICT4361-1.
 * Author: Raymond G Menasche
 */
package edu.du.menascheraymond.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author raymond
 */
public class VehicleFrame extends javax.swing.JFrame {

    /**
     * Creates new form VehicleForm
     */
    public VehicleFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vehiclesList = new javax.swing.JList<>();
        ownersVehiclesLabel = new javax.swing.JLabel();
        ownerLabel = new javax.swing.JLabel();
        manufacturerLabel = new javax.swing.JLabel();
        modelYearLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        subModelLabel = new javax.swing.JLabel();
        classificationLabel = new javax.swing.JLabel();
        insuredLabel = new javax.swing.JLabel();
        manufacturerField = new javax.swing.JTextField();
        modelYearField = new javax.swing.JTextField();
        modelField = new javax.swing.JTextField();
        subModelField = new javax.swing.JTextField();
        insuredCheckBox = new javax.swing.JCheckBox();
        classificationCombo = new javax.swing.JComboBox<>();
        addVehicleButton = new javax.swing.JButton();
        removeVehicleButton = new javax.swing.JButton();
        searchOwnerIdField = new javax.swing.JTextField();
        ownerSearchButton = new javax.swing.JButton();
        ownerResultLabel = new javax.swing.JLabel();
        vehicleMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        undoResetMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vehicles");

        vehiclesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(vehiclesList);

        ownersVehiclesLabel.setText("Owner's Vehicles");

        ownerLabel.setText("Owner ID");

        manufacturerLabel.setText("Manufacturer");

        modelYearLabel.setText("Model Year");

        modelLabel.setText("Model");

        subModelLabel.setText("Sub Model");

        classificationLabel.setText("Classification");

        insuredLabel.setText("Insured");

        classificationCombo.setMaximumRowCount(3);
        classificationCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ANTIQUE", "CLASSIC", "MODERN" }));

        addVehicleButton.setText("Add");

        removeVehicleButton.setText("Remove");

        ownerSearchButton.setText("Search");

        ownerResultLabel.setText("Owner Result Display");

        fileMenu.setText("File");

        exitMenuItem.setText("Exit");
        fileMenu.add(exitMenuItem);

        vehicleMenuBar.add(fileMenu);

        editMenu.setText("Edit");

        undoResetMenuItem.setText("Undo/Reset");
        editMenu.add(undoResetMenuItem);

        vehicleMenuBar.add(editMenu);

        setJMenuBar(vehicleMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ownerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manufacturerLabel)
                            .addComponent(modelYearLabel)
                            .addComponent(modelLabel)
                            .addComponent(subModelLabel)
                            .addComponent(classificationLabel)
                            .addComponent(insuredLabel))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchOwnerIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(ownerSearchButton))
                    .addComponent(manufacturerField)
                    .addComponent(modelYearField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modelField)
                    .addComponent(subModelField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(insuredCheckBox)
                    .addComponent(classificationCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ownerResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(ownersVehiclesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(ownersVehiclesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ownerLabel)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(searchOwnerIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ownerSearchButton)
                                        .addComponent(ownerResultLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(manufacturerLabel)
                                    .addComponent(manufacturerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(modelYearLabel)
                                    .addComponent(modelYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addVehicleButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(modelLabel)
                                    .addComponent(modelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(subModelLabel)
                                    .addComponent(subModelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(classificationLabel)
                                    .addComponent(classificationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(removeVehicleButton)
                                .addGap(119, 119, 119)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insuredLabel)
                            .addComponent(insuredCheckBox))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VehicleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VehicleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VehicleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VehicleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VehicleFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVehicleButton;
    private javax.swing.JComboBox<String> classificationCombo;
    private javax.swing.JLabel classificationLabel;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JCheckBox insuredCheckBox;
    private javax.swing.JLabel insuredLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField manufacturerField;
    private javax.swing.JLabel manufacturerLabel;
    private javax.swing.JTextField modelField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelYearField;
    private javax.swing.JLabel modelYearLabel;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JLabel ownerResultLabel;
    private javax.swing.JButton ownerSearchButton;
    private javax.swing.JLabel ownersVehiclesLabel;
    private javax.swing.JButton removeVehicleButton;
    private javax.swing.JTextField searchOwnerIdField;
    private javax.swing.JTextField subModelField;
    private javax.swing.JLabel subModelLabel;
    private javax.swing.JMenuItem undoResetMenuItem;
    private javax.swing.JMenuBar vehicleMenuBar;
    private javax.swing.JList<String> vehiclesList;
    // End of variables declaration//GEN-END:variables

    public JButton getAddVehicleButton() {
        return addVehicleButton;
    }

    public JComboBox<String> getClassificationCombo() {
        return classificationCombo;
    }

    public JLabel getClassificationLabel() {
        return classificationLabel;
    }

    public JMenu getEditMenu() {
        return editMenu;
    }

    public JMenuItem getExitMenuItem() {
        return exitMenuItem;
    }

    public JMenu getFileMenu() {
        return fileMenu;
    }

    public JCheckBox getInsuredCheckBox() {
        return insuredCheckBox;
    }

    public JLabel getInsuredLabel() {
        return insuredLabel;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTextField getManufacturerField() {
        return manufacturerField;
    }

    public JLabel getManufacturerLabel() {
        return manufacturerLabel;
    }

    public JTextField getModelField() {
        return modelField;
    }

    public JLabel getModelLabel() {
        return modelLabel;
    }

    public JTextField getModelYearField() {
        return modelYearField;
    }

    public JLabel getModelYearLabel() {
        return modelYearLabel;
    }

    public JLabel getOwnerLabel() {
        return ownerLabel;
    }

    public JLabel getOwnerResultLabel() {
        return ownerResultLabel;
    }

    public JButton getOwnerSearchButton() {
        return ownerSearchButton;
    }

    public JLabel getOwnersVehiclesLabel() {
        return ownersVehiclesLabel;
    }

    public JButton getRemoveVehicleButton() {
        return removeVehicleButton;
    }

    public JTextField getSearchOwnerIdField() {
        return searchOwnerIdField;
    }

    public JTextField getSubModelField() {
        return subModelField;
    }

    public JLabel getSubModelLabel() {
        return subModelLabel;
    }

    public JMenuItem getUndoResetMenuItem() {
        return undoResetMenuItem;
    }

    public JMenuBar getVehicleMenuBar() {
        return vehicleMenuBar;
    }

    public JList<String> getVehiclesList() {
        return vehiclesList;
    }


}
